#!/bin/sh /etc/rc.common
######################################################################
# smp_affinity - Pin IRQs to specific CPUs for better performance
######################################################################

START=93
PROG="smp_affinity"

cpus_to_bitmask() {
  local bitmask=0
  # shellcheck disable=2048
  for range in ${*//,/ }; do
    local start="${range%-*}"
    local end="${range#*-}"
    if [ -z "$end" ]; then
      bitmask="$((bitmask | 1 << start))"
    else
      bitmask="$((bitmask | (2 ** (end - start + 1) - 1) << start))"
    fi
  done
  printf '%x' "$bitmask"
}

set_affinity() {
  local pattern="$1"
  local affinity="$2"
  local bitmask="$(cpus_to_bitmask "$affinity")"

  awk -v pat="$pattern" '$NF ~ pat { print substr($1, 1, length($1)-1), $NF }' /proc/interrupts | \
  while read -r irq name; do
    if [ -n "$irq" ] && echo "$bitmask" > "/proc/irq/$irq/smp_affinity" 2>/dev/null; then
      [ "$enable_log" = "true" ] && \
        logger -t "$PROG" "$(printf "Pinned IRQ(%s) %-24s to CPU %s" "$irq" "$name" "$affinity")"
    fi
  done
}

enable_affinity_ipq60xx() {
  # NSS Queues
  set_affinity '^nss_queue0$' 0
  set_affinity '^nss_queue1$' 1
  set_affinity '^nss_queue2$' 2
  set_affinity '^nss_queue3$' 3

  # Wi-Fi PPDU MAC
  set_affinity '^ppdu-end-interrupts-mac1$' 1
  set_affinity '^ppdu-end-interrupts-mac2$' 2

  # REO status
  set_affinity '^reo2host-status$' 0

  # Crypto Engine (ce0, ce1, ..., ce11)
  set_affinity '^ce[0-9]+$' 3

  # USB
  set_affinity '^xhci-hcd:usb1$' 3

  # NSS misc
  set_affinity '^nss_empty_buf_sos$' 0
  set_affinity '^nss_empty_buf_queue$' 1
  set_affinity '^nss_paged_empty_buf_sos$' 2
}

start() {
  local enable

  config_load "$PROG" >/dev/null 2>&1
  
  config_get_bool enable     "general" enable     1
  config_get_bool enable_log "general" enable_log 1

  [ "$enable"     -eq 1 ] && enable=true     || enable=false
  [ "$enable_log" -eq 1 ] && enable_log=true || enable_log=false

  if $enable; then
    (
      sleep 30
      enable_affinity_ipq60xx
      [ "$enable_log" = "true" ] && logger -t "$PROG" "Affinity rules applied successfully."
    ) &
  fi
}

boot() {
  start
}