#
# https://github.com/P3TERX/Actions-OpenWrt
#
# File: .github/workflows/update-checker.yml
# Description: Source code update checker
#
# Copyright (c) 2019-2024 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: Update Checker

on:
  workflow_dispatch:
  schedule:
    - cron: 11 17 * * 2,5

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # max-parallel: 3
      matrix:
        REPO_NAME: [immortalwrt]
        REPO_PROJECT: [immortalwrt]
        REPO_BRANCH: [master]
        include:
          - REPO_NAME: qosmio
            REPO_PROJECT: openwrt-ipq
            REPO_BRANCH: main-nss
          - REPO_NAME: laipeng668
            REPO_PROJECT: immortalwrt
            REPO_BRANCH: master
          - REPO_NAME: laipeng668
            REPO_PROJECT: openwrt-6.x
            REPO_BRANCH: main-nss
          - REPO_NAME: JuliusBairaktaris
            REPO_PROJECT: openwrt-nss-edma
            REPO_BRANCH: nss-edma-rework
        #  - REPO_NAME: VIKINGYFY
        #    REPO_PROJECT: immortalwrt
        #    REPO_BRANCH: main
    steps:

    - name: Get Commit Hash
      id: getHash
      run: |
        git clone --depth 1 https://github.com/${{ matrix.REPO_NAME }}/${{ matrix.REPO_PROJECT }} -b ${{ matrix.REPO_BRANCH }} .
        echo "commitHash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

    - name: Compare Commit Hash
      id: cacheHash
      uses: actions/cache@v3
      with:
        path: .commitHash.${{ matrix.REPO_NAME }}
        key: commitHash_${{ steps.getHash.outputs.commitHash }}

    - name: Save New Commit Hash
      if: steps.cacheHash.outputs.cache-hit != 'true'
      run: |
        echo ${{ steps.getHash.outputs.commitHash }} | tee .commitHash.${{ matrix.REPO_NAME }}

    - name: Trigger build
      if: steps.cacheHash.outputs.cache-hit != 'true'
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        event-type: "Source_Code_Update_${{ matrix.REPO_NAME }}"
        client-payload: |-
          {
            "repo": {
              "url": "https://github.com/${{ matrix.REPO_NAME }}/${{ matrix.REPO_PROJECT }}",
              "branch": "${{ matrix.REPO_BRANCH }}"
            }
          }
  cleanup:
    runs-on: ubuntu-latest
    needs: check
    steps:
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 2
        delete_workflow_pattern: "Update Checker"
